# Generated by Django 3.1.4 on 2021-01-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parentComment',
            field=models.BigIntegerField(default=0),
        ),
    ]
