# Generated by Django 3.1.4 on 2020-12-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(default=7890654321),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, default='student', max_length=100),
        ),
    ]
