# Generated by Django 3.1.4 on 2021-01-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0015_auto_20210101_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(default=0),
        ),
    ]
