# Generated by Django 3.1.4 on 2020-12-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20201225_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='cristiano', max_length=64, unique=True),
        ),
    ]
