# Generated by Django 3.1.4 on 2020-12-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
